"""add manager department

Revision ID: 1bb5679ea4b9
Revises: 7ddd008bcaaa
Create Date: 2021-11-06 22:21:14.758860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb5679ea4b9'
down_revision = '7ddd008bcaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('department', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'department')
    # ### end Alembic commands ###
